name: Makefile CI

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Service test
      run: make testservice     

    - name: Build
      run: make build tag=${{github.ref_name}}
    
    - name: Cli test
      run: make testcli

    - name: Push
      run: make push

      
